name: Check Links

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lychee
        run: cargo install lychee

      - name: Run link checker
        run: lychee --no-progress "**/*.md"
